# Generated by Django 4.1.1 on 2022-11-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientphotogallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='hideSelected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='onlySelected',
            field=models.BooleanField(default=False),
        ),
    ]
