# Generated by Django 3.1.6 on 2021-02-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210226_2133'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(fields=('listing', 'user'), name='unique item in watchlist'),
        ),
    ]
